### ISSUE TITLE
Can't prohibit closing Background Apps

### ISSUE THREAD

**Issue by FlohGro-dev** [BigBerny/magicquit#2]
Hi @BigBerny  first of all, this app is brilliant! Thank you so much!
its just cleaning up my Mac constantly and I don't have a window mess at hand :)

I would like to prevent closing apps like Cleanshot X or Recast which will be closed and I have no option to prohibit MagicQuit from closing them.

**Comment by BigBerny** [comment]
I'm aware of it and I might be able to fix it new year 😅
In the meanwhile: For some apps it helps to open the settings, then it will appear in the MagicQuit menu where you can untick it.

**Comment by FlohGro-dev** [comment]
great thank you! this worked for Recast and Better Touch Tool but e.g. not for Cleanshot X unfortunately.

Looking forward to the fix 👍🏽

**Comment by BigBerny** [comment]
I just released version 1.4 which doesn't terminate apps that run in the background anymore. 

Since there's no auto-update yet, please download it manually from https://magicquit.com or build it yourself.

Merry Christmas 🎅🏼

**Comment by FlohGro-dev** [comment]
thanks that was fast :) merry Christmas 🎄
