### ISSUE TITLE
Quitting App

### ISSUE THREAD

**Issue by alwinsamson** [BigBerny/magicquit#6]
Magicquit is quitting applications that do not appear in the list of actively running apps. For example, Raycast is unexpectedly terminated by Magicquit.

**Comment by BigBerny** [comment]
Are you using version 1.4?

**Comment by alwinsamson** [comment]
I'm using Version 1.3.1 (14)

**Comment by BigBerny** [comment]
Well, then download 1.4 from https://magicquit.com/ 😄

**Comment by ryoppippi** [comment]
hi! @BigBerny thank you for creating this.

This still happens on 1.4
